### ISSUE TITLE
[CallMeSoul]

### ISSUE THREAD

**Issue by yzqzss** [saveweb/doing#74]
ID:250﻿
https://callmesoul.cn 
的证书已于 2021/6/21 过期。

已发Q友申请。

**Comment by yzqzss** [comment]
@callmesoul

**Comment by yzqzss** [comment]
已发邮件，继续等待回复。

**Comment by callmesoul** [comment]
已解决 @yzqzss

**Comment by yzqzss** [comment]
又过期了，已发QQ消息。

**Comment by 1C8199D3C9F1** [comment]
证书已续签。

**Comment by callmesoul** [comment]
thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matatabi ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 中午11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [saveweb/doing] [CallMeSoul] (#74)





 
Closed #74.
 
&mdash;
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yzqzss** [comment]
> 证书已续签。

BOX已移动分类。
